373 cypress frontend testing lesson
savvy-coders/SPA-example-with-Express-and-Mongo pull request #38
Opened 2023-07-07 19:18 UTC by drod1107

Update to add Jasmine and Cypress basic testing for Backend and Frontend respectively - matches update to curriculum from:

https://github.com/savvy-coders/sc-curriculum/compare/373-cypress-frontend-testing-lesson

2023-07-07 20:09 UTC, matsinet approved these changes

2023-07-07 20:10 UTC, matsinet requested changes
This PR needs to target the development branch instead of master

2023-07-07 20:18 UTC, matsinet approved these changes

2023-07-07 21:18 UTC, Gerald-Lofton approved these changes

2023-07-07 21:32 UTC, SchoolyB approved these changes
LGTM

2023-08-15 18:54 UTC, matsinet approved these changes

2023-08-15 18:55 UTC, merged